# Generated by Django 2.2.3 on 2019-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190723_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='transit_price',
            field=models.DecimalField(decimal_places=2, default='5.0', max_digits=10, verbose_name='订单运费'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default='', max_length=256, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
